repos:
  # 基本检查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace  # 检查行尾空格
      - id: end-of-file-fixer    # 确保文件以换行符结束
      - id: check-yaml           # 检查 YAML 文件语法
      - id: check-json           # 检查 JSON 文件语法
      - id: check-added-large-files  # 检查是否添加了大文件
        args: ['--maxkb=500']
      - id: mixed-line-ending    # 检查混合行结束符
        args: ['--fix=lf']
      - id: check-merge-conflict  # 检查合并冲突标记
      - id: check-executables-have-shebangs  # 检查可执行文件是否有 shebang

  # Fish 脚本检查
  # 使用专门为 Fish 脚本设计的检查器
  - repo: https://github.com/hugoh/pre-commit-fish.git
    rev: v1.2
    hooks:
      - id: fish_syntax  # 检查 Fish 脚本语法
      - id: fish_indent  # 检查并修复 Fish 脚本缩进

  # 注意：我们已经使用 hugoh/pre-commit-fish 提供的 fish_syntax 钩子，
  # 因此不再需要自定义的 Fish 语法检查钩子。

  # Python 代码检查（如果项目中有 Python 代码）
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
